### ISSUE TITLE
Left sidebar context lost when subheading link clicked

### ISSUE THREAD

**Issue by markpeters-snow** [rtfd/sphinx_rtd_theme#290] opened 2016-04-11 13:58 UTC
V0.1.8 introduced support for third and fourth level headers in the sidebar. We've enabled this feature in our doc. As long as a reader only clicks in the left sidebar, the feature works well. 

If **maxdepth** is set to "3" in **layout.html** and a reader navigates to a third level page and clicks on a mini-TOC subheading link, the node in the left sidebar closes. The sidebar loses context.

Unfortunately, our doc is currently behind a firewall. When the doc goes public in the coming weeks, I'll update this issue with a clickpath to demonstrate the issue.

Thanks.

**Comment by glasserc** [comment] 2016-05-03 17:59
I think this is the same issue we've seen in https://github.com/Kinto/kinto/issues/581. http://kinto.readthedocs.io/en/latest/api/1.x/buckets.html is a good example. Clicking any of the subsection permalinks cause the sidebar menu to immediately close.

**Comment by mattklein123** [comment] 2016-08-02 20:04
+1 would love to see this fixed if the fix is easy. I'm noticing this issue as well.

**Comment by magopian** [comment] 2016-09-30 13:24
It seems that to reproduce this issue, it needs the `sphinxcontrib.httpdomain` extension enabled, and some `http:....` directive like the following one:

```
=========
TOC Tests
=========

One
===

Two
---

Three
.....


.. http:post:: /foobar

    :synopsis: Some synopsis

    Some content

```
Beware, you need to make sure that there's a toctree enabled for this page in your `index.rst`,
for example with
```
.. toctree::
    :maxdepth: 2
```

Clicking on any of the headers from `One` to `Three` will correctly update the left navigation bar, and highlight the proper entries. The url is then `http://localhost:1919/toc.html#three`

<img width="587" alt="screen shot 2016-09-30 at 15 22 13" src="https://cloud.githubusercontent.com/assets/167767/18993051/c0715d12-8721-11e6-973c-f621030c7eb2.png">


Clicking on the `POST /foobar` item link in the page will "loose all the context", and close the sidebar navigation. The url is then `http://localhost:1919/toc.html#post--foobar`

<img width="592" alt="screen shot 2016-09-30 at 15 22 27" src="https://cloud.githubusercontent.com/assets/167767/18993063/c68fa190-8721-11e6-986c-fc9506c04aae.png">

**Comment by magopian** [comment] 2016-09-30 14:31
Ok so found why this was happening: the link generated by sphinxcontrib.httpdomain is a `headerlink` (which is nice), but it's not picked up by the toctree in the sidebar. So when we try matching the `window.location.hash` to an existing item in the sidebar, we don't find it, and thus close everything.

The idea of the fix in https://github.com/snide/sphinx_rtd_theme/pull/330 is to instead take the hash of the closest section/header, and use that instead to not lose the context.

As a heads up, there's another bug that makes the sidebar really weird when there's more than 3 levels (try clicking on "Four //five" and see that it's 1/ not displayed with a correct indentation in the sidebar 2/ is not displayed as "current"). I believe this is a totally unrelated bug.

<img width="593" alt="screen shot 2016-09-30 at 16 30 23" src="https://cloud.githubusercontent.com/assets/167767/18995179/592153a6-872b-11e6-97aa-cab97ffe852b.png">

**Comment by mattklein123** [comment] 2016-09-30 16:51
FWIW, I can reproduce this all over the place on the Envoy docs: https://lyft.github.io/envoy/docs/index.html

And although the Envoy docs do use httpdomain, the problem occurs even where there is no httpdomain data.

For example, this link: https://lyft.github.io/envoy/docs/intro/arch_overview/cluster_manager.html#arch-overview-cluster-manager

does not open the left side TOC to the right level.

**Comment by magopian** [comment] 2016-09-30 17:25
Mmmm, not sure it's the same root cause. In your case, it seems that as soon as you click on the top-level section/title of a documentation page, it adds this hash that doesn't correspond to any TOC entry on the left.

Can you reproduce the same issue by clicking on something else that the very top-level section link?

I would bet that this is yet another bug, not related to this one, but I could be wrong ;)

**Comment by mattklein123** [comment] 2016-09-30 17:47
"Can you reproduce the same issue by clicking on something else that the very top-level section link?" sorry not sure what that means exactly. The left side TOC not expanding issue is very easy to repro for me. Basically if I click on any `ref` that points to a TOC entry at level 3 or greater, it doesn't expand. Here is the docs source if you are interested:
https://github.com/lyft/envoy/tree/master/docs

**Comment by magopian** [comment] 2016-09-30 17:57
Let me give you an example:

Go to https://lyft.github.io/envoy/docs/configuration/cluster_manager/sds_api.html (it's at level 3 in the TOC on the left).

Now if you click on the link of the top title (see screenshot below), the bug occurs:
<img width="1112" alt="screen shot 2016-09-30 at 19 51 22" src="https://cloud.githubusercontent.com/assets/167767/19001451/8f762384-8747-11e6-9349-a2830ed0ec79.png">
This is what I'm calling "top level section link".

Now, on the same page, if you click on "Host Json" (which is a level 4 item in the TOC), there's no bug, it works fine:
<img width="816" alt="screen shot 2016-09-30 at 19 54 01" src="https://cloud.githubusercontent.com/assets/167767/19001517/d5af1dce-8747-11e6-8336-c799eb085acc.png">


That's why I'm guessing the issue you're detailing is due to another bug than the one I detailed and fixed above.

**Comment by mattklein123** [comment] 2016-09-30 18:05
Ah I see. OK. I just wanted to point out that it happens not just on those links, but also on embeded `ref` links in the text as well. It's probably the same issue.

**Comment by markpeters-snow** [comment] 2016-10-13 12:05
Will Mathieu Agopian's fix be merged into a future sphinx_rtd_theme
release? I'm experiencing the described issue, too, and am interested in
the fix.

Thanks,
Mark

**Comment by markpeters-snow** [comment] 2016-11-01 13:39
Bumping this request for information.

Will Mathieu Agopian's fix be merged into a future sphinx_rtd_theme
release? I'm experiencing the described issue, too, and am interested in
the fix.

Thanks,
Mark

**Comment by mattklein123** [comment] 2017-02-22 03:54
@magopian I thought that https://github.com/snide/sphinx_rtd_theme/commit/afaf0dc9bddf19e34658e661b3c3c2a7d4dfa265 would fix my Envoy docs issue, but I tested it out and indeed you are correct above that my issue is not the same issue. 

Any chance of getting the other issue fixed with L3 and L4 links? I can give you lots of different repros if needed.

**Comment by Blendify** [comment] 2017-03-15 00:18
The initial issue is fixed. For those of you experiencing different/similar issues please open a new report.

**Closed by Blendify** 2017-03-15 00:18 UTC

**Comment by mattklein123** [comment] 2017-03-15 00:23
@Blendify I have repo instructions in this issue which are still broken. You want me to copy them out to a new issue?

**Comment by Blendify** [comment] 2017-03-15 00:28
Yes please. It is easier to follow that way.
