### ISSUE TITLE
Equation numbers positioned wrong

### ISSUE THREAD

**Issue by Gabriel-p** [rtfd/sphinx_rtd_theme#150] opened 2014-09-19 17:41 UTC
This is how I see some equations displayed locally:

![captura de pantalla de 2014-09-19 12 07 40](https://cloud.githubusercontent.com/assets/6054951/4337361/bcaedcb0-400e-11e4-923f-83f2a117578f.png)

notice the equation numbers to the _right_.

This is how I see them [live](http://asteca.readthedocs.org/en/latest/int_mags.html):

![captura de pantalla de 2014-09-19 12 08 44](https://cloud.githubusercontent.com/assets/6054951/4337376/e0b55260-400e-11e4-9444-f2bb8ecc9ded.png)

notice the different location of the numbers to the _left_ of the equations, positioned far too close and not aligned.

**Comment by Blendify** [comment] 2017-03-08 19:02
This is a duplicate of #301 closing

**Closed by Blendify** 2017-03-08 19:02 UTC
