### ISSUE TITLE
Integrate docson in theme

### ISSUE THREAD

**Issue by paulmeems-waterwatchfoundation** [rtfd/sphinx_rtd_theme#735] opened 2019-02-28 20:15 UTC
### Problem

Can't include more than 1 docson widget

### Reproducible Project

I'm not sure if this is the right place to ask.  I'm trying to integrate docson widgets in my ReadTheDocs, but I can't get it to work with multiple widgets.
I explained in more detail at https://stackoverflow.com/questions/54706831/how-to-use-docson-widget-with-sphinx-on-readthedocs

#### Expected Results

Show multiple docson widgets on the same page

### Environment Info

- Python Version: v3.7.2
- Sphinx Version: v1.8.4
- RTD Theme Version:

**Comment by Blendify** [comment] 2019-02-28 22:42
Not sure on your error but follow this guide for adding css/js

https://docs.readthedocs.io/en/stable/guides/adding-custom-css.html

**Comment by Blendify** [comment] 2019-03-06 15:30
Closing as this is not a bug/error of the theme itself.

**Closed by Blendify** 2019-03-06 15:30 UTC
