### ISSUE TITLE
equation number label not floating right

### ISSUE THREAD

**Issue by emptymalei** [rtfd/sphinx_rtd_theme#169] opened 2015-02-23 22:28 UTC
One example:

http://prsm.readthedocs.org/math.html#equation-EQrelativityMetricPoint

![image](https://cloud.githubusercontent.com/assets/663798/6339009/26380634-bb70-11e4-8b8c-cdae50e60393.png)

The config for math is [here](https://github.com/CosmologyTaskForce/PhysicsResearchSurvivalManual/blob/master/conf.py#L29) .

---

So I added a `float:right;` to the span inside math p,

![image](https://cloud.githubusercontent.com/assets/663798/6339049/818ccc7c-bb70-11e4-9dfd-107798517691.png)

Now it works.

**Comment by mgeier** [comment] 2015-10-22 09:08
This seems to be a duplicate of #150.

It would be great if this could be fixed!

**Comment by Blendify** [comment] 2017-03-08 19:02
This is a duplicate of https://github.com/rtfd/sphinx_rtd_theme/issues/301 closing

**Closed by Blendify** 2017-03-08 19:02 UTC

**Comment by oholimoli** [comment] 2021-01-20 08:30
This issue is still not resolved :/
