### ISSUE TITLE
Pygments monokai style console highlighting

### ISSUE THREAD

**Issue by studentism** [rtfd/sphinx_rtd_theme#589] opened 2018-03-16 08:15 UTC
# Issue
monokai highlighting with BashSessionLexer doesn't highlight the console prompt in the same  manner as Pygments (compared to, say, http://pygments.org/demo). I am aware of #503, and I'm using the master branch, which does match the behavior of any other Pygment styles I've tested.

[edit]: Just to clarify, this behavior doesn't exist with Python's interactive prompt.

# Config
- Sphinx 1.5.6, Pygments 2.2.0
 - master's `sphinx_rtd_theme`dir (checked out just now) in my project's `_themes` dir
 - a conf.py file with the following relevant settings:

```
pygments_style = 'monokai'
html_theme = 'sphinx_rtd_theme'
html_theme_path = ["_themes"]
```
- the following snippet

```rst
.. code-block:: console

$ echo "Hello!"
```
# Output Comparison

## Pygment's `monokai` style
via sphinx-build, pre-#503 fix:
![screen shot 2018-03-16 at 01 03 04](https://user-images.githubusercontent.com/142393/37509763-e0078d0e-28b5-11e8-84cf-3d3e9dd832b0.png)
via sphinx-build, using master:
![screen shot 2018-03-16 at 00 43 48](https://user-images.githubusercontent.com/142393/37509090-1fe7b78a-28b3-11e8-95b8-9b9573b3c943.png)
via Pygments, directly:
![screen shot 2018-03-16 at 00 41 39](https://user-images.githubusercontent.com/142393/37509026-d3c91150-28b2-11e8-9fef-177e07e66ca6.png)

## Contrast with Pygment's `friendly` style  (as one example):
via sphinx-build, pre-#503 fix:
![screen shot 2018-03-16 at 00 53 49](https://user-images.githubusercontent.com/142393/37509442-98a37208-28b4-11e8-9dde-b2211f5caa0d.png)
via sphinx-build, using master:
![screen shot 2018-03-16 at 00 56 38](https://user-images.githubusercontent.com/142393/37509530-ed265f02-28b4-11e8-8120-fbae5822bab0.png)
via Pygments, directly:
![screen shot 2018-03-16 at 01 01 00](https://user-images.githubusercontent.com/142393/37509686-906eadfe-28b5-11e8-8a8a-cccade5b1840.png)

The last two comparisons of each style are the relevant ones; I only included the first to demonstrate that I'm not completely off with my configuration. Assuming it's not a PEBCAK, this is certainly a minor issue. I just prefer monokai's coloring scheme.

All apologies for poor screenshot formatting and for not having the time at present to investigate/generate a pull request.

**Comment by Blendify** [comment] 2018-03-18 16:48
Have you tested with other Sphinx themes? Try just using `html_theme = 'basic`.

**Comment by jessetan** [comment] 2018-03-20 09:35
This does not seem like a bug to me. The HTML generated looks like this:
```html
<div class="highlight">
    <pre>
        <span></span>
        <span class="gp">$</span>
        <span class="nb">echo</span>
        <span class="s2">"hello"</span>
    </pre>
</div>
```

The prompt gets the `.gp` (Generic Prompt) CSS class. In the monokai style. This class [not been assigned a color in Pygments `monokai.py`](https://bitbucket.org/birkenfeld/pygments-main/src/7941677dc77d4f2bf0bbd6140ade85a9454b8b80/pygments/styles/monokai.py?at=default&fileviewer=file-view-default#monokai.py-102).
Other styles (like `friendly`) do define a color for `.gp`.

How did you get the output in your screenshot "via Pygments, directly"?

**Comment by Blendify** [comment] 2018-04-12 13:17
Is there a bug in the theme here? Or should we close this?

**Comment by jessetan** [comment] 2018-04-13 08:35
I think we can close it; it's not a bug of the theme but the way Pygments gives us the colors. If this is not what users want, they should provide custom CSS for the Pygments highlighting or file an issue/PR for Pygments to change the color.

**Comment by Blendify** [comment] 2018-04-13 15:34
Any reason why you re-opened this @stsewd

**Closed** 2018-04-18 02:13 UTC

**Comment by stsewd** [comment] 2018-04-18 02:14
@Blendify sorry, It was by mistake.
