### ISSUE TITLE
Collapsible navigation menu

### ISSUE THREAD

**Issue by AstroMatt** [rtfd/sphinx_rtd_theme#715] opened 2019-01-17 22:43 UTC
### Problem

Couple of years ago I started a book on Python 3 and Machine Learning on Read The Docs. Now it is 917 pages long documen. I have some serious problems with navigating menu - it is too long. People are complaining, that it is very hard to look for information.

Can you please add collapsible sections to menu and ability to set default as collapsed?

### Reproducible Project

http://python.astrotech.io

### Environment Info

- Python Version: 3.7.2
- Sphinx Version: 1.8.3
- RTD Theme Version: 0.4.2

**Comment by humitos** [comment] 2019-01-21 15:04
Hi @AstroMatt! I'm not sure to follow your request. Accessing to your project I do see the navigation menu collapsed at the beginning and then when click on one of the items, it expands showing more inner contents

![captura de pantalla_2019-01-21_16-03-06](https://user-images.githubusercontent.com/244656/51482233-31d73c80-1d96-11e9-9bcd-ca40cf0a5061.png)

**Comment by AstroMatt** [comment] 2019-01-21 18:38
I was thinking about the whole menu at the left side which is several screens long and has couple of dozens of entries. Toctree caption like “data types” is not numbered and it is expanded. When I number it manually, it breaks PDF.



there is also a small problem with Tocree caption, and headers in index.rst. In order to render chapters in PDF properly, I have to use both of them (header and toctree caption). Which makes double titles on rendered index.html.


PS. I am using RTD for couple of my books and I really appreciate what you’re doing. Thank you very much!!

**Comment by jessetan** [comment] 2019-01-26 19:53
Have you considered making

**Comment by AstroMatt** [comment] 2019-01-27 10:57
I am using something like that:

```
************
Introduction
************
.. toctree::
    :maxdepth: 2
    :numbered:
    :caption: Introduction

    /about/install.rst
    /about/language.rst
    /about/syntax.rst
```

Whole file, here:
https://raw.githubusercontent.com/AstroMatt/book-python/master/index.rst

Is there a better way to create chapters?

**Comment by stsewd** [comment] 2019-02-21 12:20
Maybe https://github.com/rtfd/sphinx_rtd_theme/issues/336 is what you mean?

**Comment by Blendify** [comment] 2019-03-06 19:49
This is not a bug in the theme but more of a limitation of sphinx itself. The solution I would recommend is:
https://github.com/rtfd/sphinx_rtd_theme/issues/715#issuecomment-457860506

> there is also a small problem with Tocree caption, and headers in index.rst. In order to render chapters in PDF properly, I have to use both of them (header and toctree caption). Which makes double titles on rendered index.html.

I would report this to sphinx itself, I too have found this a problem.

As a theme we just interpret what sphinx generate and apply styling. Nothing we can really do here, closing.

**Closed by Blendify** 2019-03-06 19:49 UTC
Labels: Support
