### ISSUE TITLE
Don’t show “Edit on GitHub” link on docs generated from modules

### ISSUE THREAD

**Issue by alexwlchan** [rtfd/sphinx_rtd_theme#324] opened 2016-09-04 18:44 UTC
Moving from https://github.com/pyca/cryptography/issues/3137 – if you have a docs page generated from a module, it shows an “Edit on GitHub” link that points to a non-existent RST file.

It would be nice to either:
- Point that link at the correct file, or
- Hide the link when it points to a non-existent page

I have a vague memory of doing something similar once before, so I might have a go at this when I’m a bit less busy.

**Comment by alexwlchan** [comment] 2016-09-04 18:46
Aha, found it: 6360a2e.

Not quite the same because I was hiding the link on a page which didn’t have a corresponding source file – but as a short-term fix, something like that might be better than leaving broken links around.

**Comment by Blendify** [comment] 2017-03-14 00:07
Duplicate of https://github.com/rtfd/sphinx_rtd_theme/issues/252

**Closed by Blendify** 2017-03-14 00:07 UTC
Labels: Status: duplicate
