### ISSUE TITLE
TOC fails to indent sub sections

### ISSUE THREAD

**Issue by giampaolo** [rtfd/sphinx_rtd_theme#89] opened 2014-01-22 08:21 UTC
Say you have a main section and a subsection, like this:

```
System related functions
========================

blah blah 

CPU

---

blah blah 
```

The table of contents included in the left bar should indent the "CPU" section so that visually it appears as a child of the "System related functions" section, but it doesn't.
Practical example is psutil doc:
http://psutil.readthedocs.org/en/latest/

**Comment by ssbarnea** [comment] 2015-08-04 13:18
I have the same problem with my libraries. I am pretty sure it was working few months ago so I guess is not my documentation which was (sadly) not touched for a long long time.

I am wondering what was the problem and the solution. Also wondering if there is a way to change the default collapsed-state of a specific section.

**Comment by Blendify** [comment] 2017-03-15 00:44
Closing, from the example everything sounds like it is working as intended. CPU is not a headline.

**Closed by Blendify** 2017-03-15 00:44 UTC
