### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by kassbohm** [rtfd/sphinx_rtd_theme#398] opened 2017-03-20 12:20 UTC
Hi, searching in my html-doc does not work.

What happens is: 

1) I enter a string in the search-field.
2a) if that string does **not** exists:  I get shown immediately, that no results are found. So this is ok. But:
2b) if that string does exist, search runs forever and does not come up with results. 
 
I do or did this:
A) install via: $ pip install sphinx_rtd_theme
B) use sphinx 1.5.3 and have created a new doc with: sphinx-quickstart
C) add the following at the end of conf.py:

import sphinx_rtd_theme
html_theme = "sphinx_rtd_theme"
html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]

Any ideas? I saw that some people have problems with this. But I could not find a solution...

**Comment by Blendify** [comment] 2017-03-20 21:46
This is a duplicate of https://github.com/rtfd/sphinx_rtd_theme/issues/348

**Closed by Blendify** 2017-03-20 21:46 UTC

**Comment by kassbohm** [comment] 2017-03-20 22:07
sorry about this.
Thanks for letting me know.
K
