### ISSUE TITLE
Read The Docs panel in the menu on left bottom side does not open in Google Chrome and FireFox

### ISSUE THREAD

**Issue by krzychb** [rtfd/sphinx_rtd_theme#563] opened 2018-01-30 14:18 UTC
### Problem

Read The Docs panel in the menu on left bottom side does not open in Google Chrome and FireFox for https://espressif-docs.readthedocs-hosted.com/projects/esp-idf/en/latest/

Original issue report: https://github.com/rtfd/readthedocs.org/issues/3563

### Reproducible Project

https://espressif-docs.readthedocs-hosted.com/projects/esp-idf/en/latest/

#### Error Logs/Results

The panel does not open in Google Chrome (checked on Windows 7) and FireFox (checked on Ubuntu 16.04). The good news is that it opens in IE on Windows 7 :)
The issue happened in last 3 days. Previously everything regarding this panel was working fine.

![image](https://user-images.githubusercontent.com/12953787/35506290-10daf57e-04e9-11e8-8f15-847e0dc5c677.png)

#### Expected Results

The panel should open when clicking. 

![image](https://user-images.githubusercontent.com/12953787/35506350-46c4f662-04e9-11e8-8d68-60f7a663bcc2.png)

### Environment Info

- Python Version: python2.7
- Sphinx Version: sphinx==1.6.5
- RTD Theme Version: sphinx-rtd-theme<0.3

**Comment by jessetan** [comment] 2018-01-31 09:36
The error is `Uncaught ReferenceError: _gaq is not defined` caused by some issue with Google Analytics not being available. Either an issue of RTD , the Sphinx extension, or both.
Not related to this theme which does nothing with GA, closing this issue.

**Closed by jessetan** 2018-01-31 09:36 UTC
