### ISSUE TITLE
Extra padding in "literalinclude" directive

### ISSUE THREAD

**Issue by argaen** [rtfd/sphinx_rtd_theme#417] opened 2017-04-27 19:06 UTC
## Details

* Project URL: http://aiocache.readthedocs.io/en/latest/
* Build URL (if applicable): https://readthedocs.org/projects/aiocache/builds/5324336/ (happens in any build)
* Read the Docs username (if applicable): argaen

## Expected Result

the code snippets should appear without the extra bottom padding. Only happens when using the `literalinclude` directive. For example in the two big code snippets in http://aiocache.readthedocs.io/en/latest/configuration.html.

## Actual Result

Extra padding added coming I don't know from where:

![screenshot from 2017-04-23 12-28-21](https://cloud.githubusercontent.com/assets/3578154/25312703/617e9f2c-2820-11e7-85c4-060d29c1115e.png)

**Comment by klas-genestack** [comment] 2017-05-17 17:56
It was fine at least in v0.1.9 (I've just updated from it).

**Comment by klas-genestack** [comment] 2017-05-18 07:12
I've `bisect`ed this issue:
```
f22bfd278ef369e7de7ac7789b59622c1ddd53ab is the first bad commit
commit f22bfd278ef369e7de7ac7789b59622c1ddd53ab
Author: Denis Volpato Martins <denis@ostec.com.br>
Date:   Mon Dec 5 12:35:53 2016 -0200

    Add 'Edit on GitLab' support

:100644 100644 1c15151d6d896298dbfa1c6bf998be8db31f4d51 ac708862f724da85c83667452d2c008b86db1be7 M	bower.json
:040000 040000 bd056e6f5ebb7726aad75c8fae6f4b5e3c340445 6251f5c40614b878b9c929cb01e3a2765186d44e M	sass
:040000 040000 227bee87670b068757a893aff7a932c4b125544e aa2dcba71a3f70e256e15c2527611dd7f4ce4825 M	sphinx_rtd_theme
```
@denisvm, can I interest you in this? =)

**Comment by Blendify** [comment] 2017-05-18 21:19
Are you sure? That commit does nothing that might affect this.

**Comment by denisvm** [comment] 2017-05-19 02:13
@Blendify, actually @klas-genestack may be right. My changes didn't cause this issue, but when I ran `grunt`, it updated the minified CSS files, inheriting all the older modifications that were made only in the source SASS files. 

With that I've inherited the change made in #344 (Fix spacing in pre) with 7f307a840c9b95f07f11fb4daa5974f682dd3cf0. If you disable this change, it'll fix this specific issue.

**Comment by klas-genestack** [comment] 2017-05-19 09:06
@Blendify, I'm pretty sure it does (you can test yourself: I can provide you all the data, if you're interested), and I think @denisvm interprets it correctly.

**Comment by cprogrammer1994** [comment] 2017-05-20 17:39
I get the same problem.

- The [.rst file](https://raw.githubusercontent.com/cprogrammer1994/ModernGL/master/docs/Examples/01_hello_world.rst)
- The [result](https://moderngl.github.io/Examples/01_hello_world.html)
- The [included file](https://github.com/cprogrammer1994/ModernGL/blob/master/examples/GLWindow/01_hello_world.py)

**Comment by cprogrammer1994** [comment] 2017-05-20 17:46
Those are not extra lines:

In my case the file has 51 lines and the line numbers have different `height` values so those are shifted.

I just changed the `class` on the `code`:

![image](https://cloud.githubusercontent.com/assets/11232402/26278169/b63729d8-3d94-11e7-820e-d3fb252c1929.png)

and now I get

![image](https://cloud.githubusercontent.com/assets/11232402/26278175/c78e6c8c-3d94-11e7-9f72-41590d5a5d2d.png)

previously it was

![image](https://cloud.githubusercontent.com/assets/11232402/26278187/edc2ab48-3d94-11e7-9ff0-bbafeda59c97.png)

**Comment by cprogrammer1994** [comment] 2017-05-20 17:50
The problem is in the `theme.css`

```
.rst-content .highlight>pre {
    line-height: normal; /* this should be removed */
}
```

**Comment by cprogrammer1994** [comment] 2017-05-20 17:58
A quick hack to solve the issue:

Add this to a [static css](https://github.com/cprogrammer1994/ModernGL/blob/master/docs/static/css/custom.css#L19) then load it from the [conf.py](https://github.com/cprogrammer1994/ModernGL/blob/master/docs/conf.py#L159)

```
.rst-content .highlight>pre {
    line-height: 18px;
}
```

**Comment by TonyFlury** [comment] 2017-07-02 18:22
Sorry if this is the wrong place to add this comment, but any idea when this will get fixed ? I use the rtd theme a lot and a quick fix would be useful.

**Comment by Blendify** [comment] 2017-12-16 22:38
#504 *Should fix* this can people try using it?

**Comment by Blendify** [comment] 2018-01-14 20:41
Im closing this issue if people still have an issue after using latest master then we can re-open

**Closed by Blendify** 2018-01-14 20:41 UTC
Labels: Needed: more information

**Comment by TonyFlury** [comment] 2018-01-15 07:01
Can someone state when this latest master will be deployed on pypi ? I don’t want my documentation to be based on non released builds of the ‘latest master’

**Comment by cprogrammer1994** [comment] 2018-01-15 07:54
Using the sphinx_rtd_theme from PyPI:

![image](https://user-images.githubusercontent.com/11232402/34931821-38d1c730-f9d9-11e7-9369-a7e100a76e7d.png)

the bug is still present

---

Using the sphinx_rtd_theme from github:

the bug is fixed

```
python -m pip install https://github.com/rtfd/sphinx_rtd_theme/archive/master.zip -U
```

![image](https://user-images.githubusercontent.com/11232402/34931915-91d1b21e-f9d9-11e7-8672-6b723918a645.png)

Version info:

```py
>>> import sphinx_rtd_theme
>>> sphinx_rtd_theme.__version__
'0.2.5b2'
```

**Comment by TonyFlury** [comment] 2018-01-15 15:14
Exactly - using the 'latest GIT master' is not a viable solution to be frank.
 -- 
Anthony Flury
anthony.flury@btinternet.com

**Comment by Blendify** [comment] 2018-01-15 17:26
@ericholscher @agjohnson Can we please take the steps to release 0.2.5!
