### ISSUE TITLE
Code-blocks with line nos - lines and line numbers don't line up.

### ISSUE THREAD

**Issue by TonyFlury** [rtfd/sphinx_rtd_theme#419] opened 2017-05-03 07:28 UTC
Using the rtd Theme  with this source : 

    .. code-block:: python
        :linenos:

        import tkinter as tk
        root = tk.Tk()
        w = tk.Label(root, text='Hello, world!')
        w.pack()
        root.mainloop()

The resultant rendered page has this : 

![mismatch](https://cloud.githubusercontent.com/assets/15114356/25651064/e45afe12-2fd8-11e7-9fac-4d0227f857a5.png)

**Comment by TonyFlury** [comment] 2017-05-03 07:30
It seems to be that the line nos are rendered with a line height of 1.5 - and generated html seems to also state the same line height value for the code, but there seems to be a clash between the line heights set in the theme : 

These two CSS rules get appled to the code block

    .rst-content .highlight > pre {
	line-height: normal;
   }

and : 

     div[class^="highlight"] pre {
             ....
	     line-height: 1.5;
            ....
     }

but the line-height: normal; takes precedence; changing the line-height value in the first rule results in correctly aligining line nos and code.

**Comment by Blendify** [comment] 2017-06-19 20:45
This is a duplicate of https://github.com/rtfd/sphinx_rtd_theme/issues/417

**Closed by Blendify** 2017-06-19 20:45 UTC
Labels: Status: duplicate
