### ISSUE TITLE
Auto-hiding the sidebar

### ISSUE THREAD

**Issue by gkiar** [rtfd/sphinx_rtd_theme#201] opened 2015-05-27 22:30 UTC
I am trying to configure RTD in such a way that the sidebar/sitemap is automatically hidden when a page is loaded, regardless of the page width (if you make your browser very narrow this happens anyways). Is there a theme option to make this happen?

**Comment by ericholscher** [comment] 2015-05-27 22:40
To answer, I don't believe we have an option for this, but it's definitely
something we would consider adding.

On Wed, May 27, 2015 at 3:30 PM, Greg Kiar <notifications@github.com> wrote:

> I am trying to configure RTD in such a way that the sidebar/sitemap is
> automatically hidden when a page is loaded, regardless of the page width
> (if you make your browser very narrow this happens anyways). Is there a
> theme option to make this happen?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/snide/sphinx_rtd_theme/issues/201>.
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Oregon
http://ericholscher.com

**Comment by agjohnson** [comment] 2015-06-02 19:46
There is not an option for this behavior. You could override this with some custom css and javascript though. I'd be -0 on providing this as part of the desktop display of the theme.

**Comment by Blendify** [comment] 2017-03-09 23:46
Duplicate of https://github.com/rtfd/sphinx_rtd_theme/issues/336

**Closed by Blendify** 2017-03-09 23:46 UTC
Labels: Status: duplicate
