### ISSUE TITLE
:github_url: as a theme option

### ISSUE THREAD

**Issue by 1138-4EB** [rtfd/sphinx_rtd_theme#529] opened 2017-12-24 12:00 UTC
I am trying to reproduce locally the output I get in RTD (see [readthedocs-docker-images#47](https://github.com/rtfd/readthedocs-docker-images/issues/47#issuecomment-353770010)). According to the README here, it seems that I need to manually add `:github_url:` to each page in order to have 'Edit on GitHub' instead of 'View page source'. I would expect this option to be available as a theme option, so that the same sources produce the same result in RTD and locally.

**Comment by jessetan** [comment] 2017-12-27 11:12
You can reproduce this locally by changing your `conf.py`:
```py
html_context = {
  'display_github': True,
  'github_user': 'username',
  'github_repo': 'reponame',
  'github_version': 'master'
}
```
Related to #156.

**Comment by 1138-4EB** [comment] 2017-12-27 23:47
Thanks a lot. That's exactly what I needed. However, I had to slightly modify it:

```
'display_github': True,
'github_user': 'username',
'github_repo': 'reponame',
'github_version': 'branch/doc/'
```

Note the subdir after the branch/version, and the trailing slash.

I close this, because the question is solved. But you might want to reopen it to keep track of the *pending* documentation.

**Comment by Blendify** [comment] 2018-02-01 02:57
This is a duplicate of #465

**Closed by Blendify** 2018-02-01 02:57 UTC
Labels: Needed: documentation, Status: duplicate

**Comment by peterjc** [comment] 2019-08-14 14:29
You don't need to have a slash in ``github_version``, see example here:

https://github.com/readthedocs/sphinx_rtd_theme/issues/231#issuecomment-126447493

I'll add a comment on #465.
